### ISSUE TITLE
can you fix this bug.i try all version in your mod but can't work.(bug with little maid mobx)

### ISSUE THREAD

**Issue by zingza555** [Mine-and-blade-admin/Battlegear2#176]
can you fix this?.kuroneko87 say "Already discussed this in the maid thread, I would have to change code in Battlegear mod in order to make them compatible" in this web:https://github.com/KuroNeko87/littleMaidMobX/issues/11
can you fix this bug i have hope to battle gear2 + liitle maid mob x = minecraft not crash

**Comment by zingza555** [comment]
---- Minecraft Crash Report ----
// Oh - I know what I did wrong!

Time: 6/4/2558, 16:30 น.
Description: Ticking entity

java.lang.ClassCastException: littleMaidMobX.LMM_InventoryLittleMaid cannot be cast to mods.battlegear2.api.core.InventoryPlayerBattle
at mods.battlegear2.BattlemodeHookContainerClass.onDrop(BattlemodeHookContainerClass.java:397)
at cpw.mods.fml.common.eventhandler.ASMEventHandler_19_BattlemodeHookContainerClass_onDrop_LivingDropsEvent.invoke(.dynamic)
at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
at net.minecraftforge.common.ForgeHooks.onLivingDrops(ForgeHooks.java:301)
at net.minecraft.entity.EntityLivingBase.func_70645_a(EntityLivingBase.java:937)
at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:853)
at net.minecraft.entity.player.EntityPlayer.func_71059_n(EntityPlayer.java:1232)
at littleMaidMobX.LMM_EntityLittleMaidAvatar.func_71059_n(LMM_EntityLittleMaidAvatar.java:169)
at littleMaidMobX.LMM_EntityLittleMaid.func_70652_k(LMM_EntityLittleMaid.java:929)
at littleMaidMobX.LMM_EntityAIAttackOnCollide.func_75246_d(LMM_EntityAIAttackOnCollide.java:174)
at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:103)
at net.minecraft.entity.EntityLiving.func_70619_bc(EntityLiving.java:540)
at littleMaidMobX.LMM_EntityLittleMaid.func_70619_bc(LMM_EntityLittleMaid.java:1582)
at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:1772)
at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:367)
at net.minecraft.entity.EntityAgeable.func_70636_d(SourceFile:95)
at net.minecraft.entity.passive.EntityAnimal.func_70636_d(SourceFile:37)
at littleMaidMobX.LMM_EntityLittleMaid.func_70636_d(LMM_EntityLittleMaid.java:1688)
at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1609)
at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:206)
at littleMaidMobX.LMM_EntityLittleMaid.func_70071_h_(LMM_EntityLittleMaid.java:1912)
at net.minecraft.world.World.func_72866_a(World.java:2070)
at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
at net.minecraft.world.World.func_72870_g(World.java:2034)
at net.minecraft.world.World.func_72939_s(World.java:1887)
at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
at mods.battlegear2.BattlemodeHookContainerClass.onDrop(BattlemodeHookContainerClass.java:397)
at cpw.mods.fml.common.eventhandler.ASMEventHandler_19_BattlemodeHookContainerClass_onDrop_LivingDropsEvent.invoke(.dynamic)
at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
at net.minecraftforge.common.ForgeHooks.onLivingDrops(ForgeHooks.java:301)
at net.minecraft.entity.EntityLivingBase.func_70645_a(EntityLivingBase.java:937)
at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:853)
at net.minecraft.entity.player.EntityPlayer.func_71059_n(EntityPlayer.java:1232)
at littleMaidMobX.LMM_EntityLittleMaidAvatar.func_71059_n(LMM_EntityLittleMaidAvatar.java:169)
at littleMaidMobX.LMM_EntityLittleMaid.func_70652_k(LMM_EntityLittleMaid.java:929)
at littleMaidMobX.LMM_EntityAIAttackOnCollide.func_75246_d(LMM_EntityAIAttackOnCollide.java:174)
at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:103)
at net.minecraft.entity.EntityLiving.func_70619_bc(EntityLiving.java:540)
at littleMaidMobX.LMM_EntityLittleMaid.func_70619_bc(LMM_EntityLittleMaid.java:1582)
at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:1772)
at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:367)
at net.minecraft.entity.EntityAgeable.func_70636_d(SourceFile:95)
at net.minecraft.entity.passive.EntityAnimal.func_70636_d(SourceFile:37)
at littleMaidMobX.LMM_EntityLittleMaid.func_70636_d(LMM_EntityLittleMaid.java:1688)
at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1609)
at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:206)
at littleMaidMobX.LMM_EntityLittleMaid.func_70071_h_(LMM_EntityLittleMaid.java:1912)
at net.minecraft.world.World.func_72866_a(World.java:2070)
at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
at net.minecraft.world.World.func_72870_g(World.java:2034)

-- Entity being ticked --
Details:
Entity Type: lmmx.LittleMaidX (littleMaidMobX.LMM_EntityLittleMaid)
Entity ID: 30539
Entity Name: Little Maid
Entity's Exact location: -243.07, 71.00, -16.19
Entity's Block location: World: (-244,71,-17), Chunk: (at 12,4,15 in -16,-2; contains blocks -256,0,-32 to -241,255,-17), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
Entity's Momentum: 0.10, -0.08, -0.02
Stacktrace:
at net.minecraft.world.World.func_72939_s(World.java:1887)
at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

-- Affected level --
Details:
Level name: New World
All players: 1 total; [EntityPlayerMP['LuCiFer002'/30674, l='New World', x=-245.61, y=71.00, z=-14.64]]
Chunk stats: ServerChunkCache: 629 Drop: 0
Level seed: 1372195158901005692
Level generator: ID 00 - default, ver 1. Features enabled: true
Level generator options: 
Level spawn location: World: (-244,64,-16), Chunk: (at 12,4,0 in -16,-1; contains blocks -256,0,-16 to -241,255,-1), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
Level time: 668 game time, 668 day time
Level dimension: 0
Level storage version: 0x04ABD - Anvil
Level weather: Rain time: 143285 (now: false), thunder time: 145371 (now: false)
Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
Minecraft Version: 1.7.10
Operating System: Windows 7 (amd64) version 6.1
Java Version: 1.8.0_40, Oracle Corporation
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
Memory: 840650184 bytes (801 MB) / 1060372480 bytes (1011 MB) up to 1060372480 bytes (1011 MB)
JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M -Xmx1g -Xms1g
AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
FML: MCP v9.05 FML v7.10.85.1230 Minecraft Forge 10.13.2.1230 9 mods loaded, 9 mods active
mcp{9.05} Minecraft Coder Pack Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
FML{7.10.85.1230} Forge Mod Loader Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
Forge{10.13.2.1230} Minecraft Forge Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
OldModelLoader{1.0} OldModelLoader Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
battlegear2{1.0.7.0} Mine & Blade Battlegear 2 - Bullseye Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
idChecker{1.7.10} ID Checker Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
lmmx{1.0} lmmx Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
MMMLibX{1.7.x-srg-1} MMMLibX Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
zabuton{1.0} zabuton Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
Profiler Position: N/A (disabled)
Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
Player Count: 1 / 8; [EntityPlayerMP['LuCiFer002'/30674, l='New World', x=-245.61, y=71.00, z=-14.64]]
Type: Integrated Server (map_client.txt)
Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by GotoLink** [comment]
The maid mod thinks it can spawn "players" as if they were mobs.
That will keep chunks loaded where they shouldn't, and the players won't be able to switch to day with a bed.
This is plain wrong. We have no responsibility over a mod that breaks the game anyway.
If this mods wants some player interaction, it should use FakePlayer. We are supporting it for such cases.

**Comment by zingza555** [comment]
thx

**Comment by zingza555** [comment]
fore new update
