### ISSUE TITLE
NPE Crash on world load with Blue Power

### ISSUE THREAD

**Issue by SethWilliamson** [Mine-and-blade-admin/Battlegear2#180]
**Test Environment:**
[forge-1.7.10-10.13.2.1291](http://files.minecraftforge.net/maven/net/minecraftforge/forge/index_1.7.10.html)
[liteloader-1.7.10-04](http://dl.liteloader.com/redist/1.7.10/liteloader-installer-1.7.10-04.jar)
[BluePower-1.7.10-0.2.927-universal.jar](http://minecraft.curseforge.com/mc-mods/223099-blue-power/files/2235039/download)
[QmunityLib-1.7.10-0.1.107-universal.jar](http://minecraft.curseforge.com/mc-mods/224785-qmunitylib/files/2235040/download)
[1.7.10-MB_Battlegear2-Bullseye-1.0.7.0.jar](http://minecraft.curseforge.com/mc-mods/59710-mb-battlegear-2/files/2225110/download)

```
java.lang.NullPointerException: Unexpected error
	at com.bluepowermod.client.render.RenderDebugScreen.onRenderDebugScreen(RenderDebugScreen.java:22)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_57_RenderDebugScreen_onRenderDebugScreen_RenderGameOverlayEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at mods.battlegear2.client.gui.BattlegearInGameGUI.renderGameOverlay(BattlegearInGameGUI.java:53)
	at mods.battlegear2.client.BattlegearClientEvents.postRenderOverlay(BattlegearClientEvents.java:110)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_30_BattlegearClientEvents_postRenderOverlay_Post.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at net.minecraftforge.client.GuiIngameForge.post(GuiIngameForge.java:899)
	at net.minecraftforge.client.GuiIngameForge.renderHotbar(GuiIngameForge.java:212)
	at net.minecraftforge.client.GuiIngameForge.func_73830_a(GuiIngameForge.java:141)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1038)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:990)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```
Complete log: http://slexy.org/raw/s21CU31tds (expires 2015-10-21)

Blue Power collaborator suspects Battlegear is attempting to call a render overlay event without specifying what you want to render, so I thought you might want to have a look too. Qmunity/BluePower#338

**Comment by GotoLink** [comment]
There is nothing much we can do for 1.7 state of Forge that wouldn't break our own API usage.
This will have to wait for 1.8.
Then at worst we'll simply change the event bus where those events are posted.
