### ISSUE TITLE
Flux-Infused Sword

### ISSUE THREAD

**Issue by Tsunayoshi** [Mine-and-blade-admin/Battlegear2#188]
Hi,

I can't put the Fluix-Infused Sword from RedstoneArsenal into my Sword or Shild Slot. Is there a way to whitlelist a item in the config, or is this a bug?

Greetings

**Comment by GotoLink** [comment]
You can use /weaponwield command.

**Comment by Tsunayoshi** [comment]
I am gettings this in the server console:

[18:50:35] [Server thread/ERROR]: Couldn't process command: 'weaponwield'
java.lang.ArrayIndexOutOfBoundsException: 0
        at mods.battlegear2.CommandWeaponWield.func_71515_b(CommandWeaponWield.java:74) ~[CommandWeaponWield.class:?]
        at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:94) [z.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:739) [nh.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:718) [nh.class:?]
        at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:37) [ir.class:?]
        at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:9) [ir.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]

**Comment by GotoLink** [comment]
Use tab-completion. You need to define which hand wields.

**Comment by Tsunayoshi** [comment]
ah /weaponwield current right|left while holing it in the hotbar.

Thanks a lot!
