### ISSUE TITLE
An exception is thrown

### ISSUE THREAD

**Issue by Tennik** [Mine-and-blade-admin/Battlegear2#215]
Hi!
I installed the latest version of M&B Battlegear 2 (1.0.8.2 for 1.7.10) on my server and client. The server works fine,there is no crashes and errors during initialisation and server work. But when I try to connect to the server with my client I receive an exception with my client (not server!) and client close.
There is that exception:

[01:39:23] [Client thread/FATAL]: Reported exception thrown!
net.minecraft.util.ReportedException: Ticking screen
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1664) ~[bao.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:962) ~[bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_31]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_31]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_31]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_31]
	at net.launcher.components.Game$1.run(Game.java:261) [ThreadsOfFate-Launcher.jar:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_31]
Caused by: java.lang.RuntimeException: Player inventory has been replaced with class net.minecraft.entity.player.InventoryPlayer
	at mods.battlegear2.BattlemodeHookContainerClass.onEntityJoin(BattlemodeHookContainerClass.java:61) ~[BattlemodeHookContainerClass.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_11_BattlemodeHookContainerClass_onEntityJoin_EntityJoinWorldEvent.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) ~[EventBus.class:?]
	at net.minecraft.world.World.func_72838_d(World.java:1334) ~[ahb.class:?]
	at net.minecraft.client.multiplayer.WorldClient.func_72838_d(WorldClient.java:159) ~[bjf.class:?]
	at net.minecraft.client.Minecraft.func_71353_a(Minecraft.java:2220) ~[bao.class:?]
	at net.minecraft.client.Minecraft.func_71403_a(Minecraft.java:2135) ~[bao.class:?]
	at net.minecraft.client.network.NetHandlerPlayClient.func_147282_a(NetHandlerPlayClient.java:239) ~[bjb.class:?]
	at net.minecraft.network.play.server.S01PacketJoinGame.func_148833_a(SourceFile:70) ~[hd.class:?]
	at net.minecraft.network.play.server.S01PacketJoinGame.func_148833_a(SourceFile:13) ~[hd.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) ~[ej.class:?]
	at net.minecraft.client.multiplayer.GuiConnecting.func_73876_c(SourceFile:78) ~[bcx.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1650) ~[bao.class:?]
	... 15 more
[01:39:23] [Client thread/INFO]: [net.minecraft.client.Minecraft:func_71377_b:349]: ---- Minecraft Crash Report ----
// Ooh. Shiny.

Time: 13.01.16 1:39
Description: Ticking screen

java.lang.RuntimeException: Player inventory has been replaced with class net.minecraft.entity.player.InventoryPlayer
	at mods.battlegear2.BattlemodeHookContainerClass.onEntityJoin(BattlemodeHookContainerClass.java:61)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_11_BattlemodeHookContainerClass_onEntityJoin_EntityJoinWorldEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at net.minecraft.world.World.func_72838_d(World.java:1334)
	at net.minecraft.client.multiplayer.WorldClient.func_72838_d(WorldClient.java:159)
	at net.minecraft.client.Minecraft.func_71353_a(Minecraft.java:2220)
	at net.minecraft.client.Minecraft.func_71403_a(Minecraft.java:2135)
	at net.minecraft.client.network.NetHandlerPlayClient.func_147282_a(NetHandlerPlayClient.java:239)
	at net.minecraft.network.play.server.S01PacketJoinGame.func_148833_a(SourceFile:70)
	at net.minecraft.network.play.server.S01PacketJoinGame.func_148833_a(SourceFile:13)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.client.multiplayer.GuiConnecting.func_73876_c(SourceFile:78)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1650)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:962)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.launcher.components.Game$1.run(Game.java:261)
	at java.lang.Thread.run(Unknown Source)

What can I do with that? I need your help!
Server core is Cauldron1.7.10 1240 213B, client version is 1.7.10 with forge 10.13.2.1277

**Comment by GotoLink** [comment]
This crash means Battlegear couldn't mod the game.
I blame Cauldron.

**Comment by Tennik** [comment]
And what I can do with that?
I need a serer with mods and plugins. I already have a 1.7.2 Cauldron server with that mod and its OK.
But I want to update it to 1.7.10.
Can you recommend me something to do?

**Comment by GotoLink** [comment]
Try a different version of Cauldron ?
Last discussion about Cauldron i had, people mentionned at least 5 "Bukkit based PluginAPI" forks with similar names.
You could also try a different Forge version.

**Comment by Tennik** [comment]
Ok, I will try on another, more later versions of Forge and Cauldron
Do not close that issue, please, I will write a result here

**Comment by Tennik** [comment]
Its ok with your mod. I have tried on different versions of Cauldron and forge. And I stopped on Cauldron and Forge 1403. And remove a bugged version of Optifine from my client. Mb that was a cause of exception "Ticking screen" in my client.
Thanks for your help!
