### ISSUE TITLE
Compatibility issues

### ISSUE THREAD

**Issue by BlurCloud** [Mine-and-blade-admin/Battlegear2#246]
Crashes because inventory is replaced by InfiniteInvo:
https://ghostbin.com/paste/84no4

**Comment by ALPHAFOX2332** [comment]
I am using battle gear 2 on 1.7.10 with the legends mod and whenever I try to go into duel wielding my game crashes

---- Minecraft Crash Report ----
// There are four lights!

Time: 19/12/19 12:38 PM
Description: Unexpected error

java.lang.ArrayIndexOutOfBoundsException: 152
	at com.tihyo.legends.management.LegendsRenderHelper.renderItemInFirstPerson(LegendsRenderHelper.java:290)
	at net.minecraft.client.renderer.ItemRenderer.func_78440_a(Unknown Source)
	at net.minecraft.client.renderer.EntityRenderer.func_78476_b(EntityRenderer.java:736)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1361)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1015)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.tihyo.legends.management.LegendsRenderHelper.renderItemInFirstPerson(LegendsRenderHelper.java:290)
	at net.minecraft.client.renderer.ItemRenderer.func_78440_a(Unknown Source)
	at net.minecraft.client.renderer.EntityRenderer.func_78476_b(EntityRenderer.java:736)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1361)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['ALPHAFOX23'/261, l='MpServer', x=-268.63, y=67.62, z=143.92]]
	Chunk stats: MultiplayerChunkCache: 130, 130
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-282,64,223), Chunk: (at 6,4,15 in -18,13; contains blocks -288,0,208 to -273,255,223), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 6725 game time, 6725 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 101 total; [EntityClientPlayerMP['ALPHAFOX23'/261, l='MpServer', x=-268.63, y=67.62, z=143.92], EntityCreeper['Creeper'/38, l='MpServer', x=-344.50, y=35.00, z=78.50], EntitySkeleton['Skeleton'/39, l='MpServer', x=-343.69, y=59.00, z=72.94], EntitySkeleton['Skeleton'/40, l='MpServer', x=-343.13, y=59.00, z=72.06], EntityZombie['Zombie'/41, l='MpServer', x=-344.50, y=59.00, z=72.31], EntityPig['Pig'/42, l='MpServer', x=-336.81, y=66.00, z=111.97], EntityPig['Pig'/43, l='MpServer', x=-336.81, y=66.00, z=110.34], EntityBat['Bat'/44, l='MpServer', x=-347.75, y=7.09, z=149.56], EntityCreeper['Creeper'/45, l='MpServer', x=-336.50, y=13.00, z=201.50], EntityBat['Bat'/46, l='MpServer', x=-331.22, y=34.72, z=70.25], EntityPig['Pig'/47, l='MpServer', x=-322.88, y=66.00, z=108.16], EntityCreeper['Creeper'/48, l='MpServer', x=-323.50, y=16.00, z=115.50], EntityPig['Pig'/49, l='MpServer', x=-333.50, y=66.00, z=112.16], EntityBat['Bat'/50, l='MpServer', x=-334.31, y=42.06, z=170.75], EntityZombie['Zombie'/51, l='MpServer', x=-330.50, y=13.00, z=198.50], EntityBat['Bat'/53, l='MpServer', x=-319.25, y=22.09, z=79.25], EntitySkeleton['Skeleton'/54, l='MpServer', x=-305.50, y=38.00, z=76.50], EntityZombie['Zombie'/55, l='MpServer', x=-317.50, y=12.00, z=81.50], EntityCow['Cow'/56, l='MpServer', x=-304.19, y=70.00, z=94.03], EntitySkeleton['Skeleton'/57, l='MpServer', x=-319.50, y=11.00, z=109.50], EntitySkeleton['Skeleton'/58, l='MpServer', x=-318.50, y=11.00, z=109.50], EntityZombie['Zombie'/59, l='MpServer', x=-313.50, y=44.00, z=104.50], EntityCow['Cow'/60, l='MpServer', x=-314.53, y=73.00, z=102.56], EntityCow['Cow'/61, l='MpServer', x=-305.66, y=71.00, z=103.47], EntityItem['item.tile.flower2.tulipRed'/62, l='MpServer', x=-308.16, y=65.13, z=124.38], EntityItem['item.tile.flower2.tulipRed'/63, l='MpServer', x=-307.28, y=65.13, z=125.06], EntitySkeleton['Skeleton'/64, l='MpServer', x=-305.50, y=11.00, z=159.50], EntityBat['Bat'/65, l='MpServer', x=-312.41, y=36.09, z=162.53], EntityBat['Bat'/66, l='MpServer', x=-308.25, y=42.09, z=179.56], EntityPig['Pig'/67, l='MpServer', x=-305.41, y=64.00, z=191.56], EntityPig['Pig'/68, l='MpServer', x=-312.66, y=63.00, z=211.78], EntityPig['Pig'/69, l='MpServer', x=-306.97, y=63.00, z=210.19], EntityCow['Cow'/72, l='MpServer', x=-300.06, y=71.00, z=101.03], EntityCreeper['Creeper'/73, l='MpServer', x=-295.00, y=12.00, z=170.44], EntityCreeper['Creeper'/74, l='MpServer', x=-298.50, y=15.00, z=170.50], EntityPig['Pig'/75, l='MpServer', x=-292.19, y=65.00, z=183.56], EntityChicken['Chicken'/76, l='MpServer', x=-299.47, y=63.00, z=222.59], EntityPig['Pig'/77, l='MpServer', x=-288.91, y=64.00, z=215.97], EntitySkeleton['Skeleton'/85, l='MpServer', x=-286.56, y=6.00, z=90.84], EntityCow['Cow'/86, l='MpServer', x=-274.72, y=64.00, z=96.47], EntitySkeleton['Skeleton'/87, l='MpServer', x=-280.50, y=8.00, z=127.50], EntityBat['Bat'/88, l='MpServer', x=-278.25, y=31.09, z=118.75], EntityXPOrb['Experience Orb'/89, l='MpServer', x=-280.31, y=66.25, z=115.59], EntityPig['Pig'/90, l='MpServer', x=-281.75, y=66.00, z=115.78], EntityBat['Bat'/91, l='MpServer', x=-273.25, y=45.09, z=138.25], EntityItem['item.item.swordIron'/92, l='MpServer', x=-286.22, y=68.13, z=128.63], EntityCreeper['Creeper'/93, l='MpServer', x=-274.03, y=45.00, z=146.53], EntityBat['Bat'/94, l='MpServer', x=-280.25, y=44.09, z=151.75], EntityCreeper['Creeper'/95, l='MpServer', x=-279.28, y=55.00, z=154.88], EntityCreeper['Creeper'/96, l='MpServer', x=-279.31, y=56.00, z=163.69], EntityCreeper['Creeper'/97, l='MpServer', x=-274.50, y=45.00, z=183.84], EntityChicken['Chicken'/98, l='MpServer', x=-276.56, y=64.00, z=210.53], EntityCreeper['Creeper'/105, l='MpServer', x=-269.50, y=5.00, z=65.50], EntityZombie['Zombie'/106, l='MpServer', x=-258.50, y=34.00, z=80.50], EntityItem['item.item.beefRaw'/107, l='MpServer', x=-260.41, y=66.13, z=103.41], EntityXPOrb['Experience Orb'/108, l='MpServer', x=-266.75, y=65.25, z=104.47], EntityXPOrb['Experience Orb'/109, l='MpServer', x=-258.28, y=67.25, z=118.25], EntityXPOrb['Experience Orb'/110, l='MpServer', x=-259.56, y=67.25, z=117.25], EntitySpider['Spider'/111, l='MpServer', x=-269.91, y=45.00, z=147.03], EntityCreeper['Creeper'/112, l='MpServer', x=-267.69, y=42.00, z=146.31], EntitySkeleton['Skeleton'/113, l='MpServer', x=-263.50, y=54.00, z=150.50], EntityZombie['Zombie'/114, l='MpServer', x=-258.69, y=34.00, z=217.69], EntityZombie['Zombie'/115, l='MpServer', x=-257.91, y=34.00, z=212.56], EntityZombie['Zombie'/116, l='MpServer', x=-259.13, y=37.00, z=221.53], EntityZombie['Zombie'/127, l='MpServer', x=-252.50, y=32.00, z=77.50], EntityCreeper['Creeper'/128, l='MpServer', x=-251.50, y=12.00, z=112.50], EntityZombie['Zombie'/129, l='MpServer', x=-249.09, y=21.00, z=127.41], EntitySkeleton['Skeleton'/130, l='MpServer', x=-241.06, y=13.00, z=142.47], EntityBat['Bat'/131, l='MpServer', x=-253.47, y=56.09, z=136.75], EntitySkeleton['Skeleton'/132, l='MpServer', x=-245.50, y=42.00, z=158.50], EntityZombie['Zombie'/133, l='MpServer', x=-251.22, y=33.00, z=158.44], EntityCreeper['Creeper'/141, l='MpServer', x=-232.59, y=43.00, z=73.97], EntitySquid['Squid'/142, l='MpServer', x=-226.50, y=59.28, z=96.50], EntitySquid['Squid'/143, l='MpServer', x=-228.31, y=60.28, z=96.50], EntitySquid['Squid'/144, l='MpServer', x=-226.38, y=59.34, z=94.50], EntitySkeleton['Skeleton'/145, l='MpServer', x=-232.50, y=12.00, z=123.34], EntitySkeleton['Skeleton'/146, l='MpServer', x=-224.50, y=42.00, z=175.13], EntityCreeper['Creeper'/147, l='MpServer', x=-229.88, y=40.00, z=167.50], EntityWitch['Witch'/148, l='MpServer', x=-229.34, y=40.00, z=165.50], EntityWitch['Witch'/149, l='MpServer', x=-226.50, y=39.00, z=166.50], EntityBat['Bat'/150, l='MpServer', x=-239.56, y=12.72, z=185.47], EntityZombie['Zombie'/151, l='MpServer', x=-235.97, y=12.00, z=200.34], EntityZombie['Zombie'/162, l='MpServer', x=-209.44, y=25.00, z=109.22], EntityZombie['Zombie'/163, l='MpServer', x=-223.56, y=11.00, z=139.75], EntitySpider['Spider'/164, l='MpServer', x=-211.50, y=51.00, z=131.50], EntityZombie['Zombie'/165, l='MpServer', x=-222.09, y=33.00, z=156.41], EntityWitch['Witch'/166, l='MpServer', x=-223.50, y=39.00, z=166.50], EntityCreeper['Creeper'/167, l='MpServer', x=-223.03, y=47.00, z=181.50], EntityZombie['Zombie'/171, l='MpServer', x=-205.50, y=56.00, z=86.50], EntityCow['Cow'/172, l='MpServer', x=-195.34, y=65.00, z=89.13], EntityCow['Cow'/173, l='MpServer', x=-196.34, y=72.00, z=103.53], EntityCow['Cow'/174, l='MpServer', x=-194.19, y=72.00, z=103.50], EntityCow['Cow'/175, l='MpServer', x=-196.56, y=71.00, z=98.53], EntitySkeleton['Skeleton'/176, l='MpServer', x=-202.31, y=15.00, z=127.50], EntitySkeleton['Skeleton'/177, l='MpServer', x=-205.44, y=21.00, z=116.44], EntityZombie['Zombie'/179, l='MpServer', x=-195.06, y=53.00, z=174.47], EntityZombie['Zombie'/180, l='MpServer', x=-193.50, y=49.00, z=179.50], EntityZombie['Zombie'/191, l='MpServer', x=-190.69, y=11.00, z=122.50], EntityBat['Bat'/193, l='MpServer', x=-189.25, y=51.09, z=166.50], EntitySkeleton['Skeleton'/194, l='MpServer', x=-191.09, y=20.00, z=190.50], EntitySkeleton['Skeleton'/195, l='MpServer', x=-189.47, y=20.00, z=189.44]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:927)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 298049376 bytes (284 MB) / 704643072 bytes (672 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -Xmx2048M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 15, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	legends{4.3} [Legends Mod] (1Legends-1.7.10-4.3.jar) 
	UCHIJAAAA	battlegear2{1.7.10} [Mine & Blade Battlegear 2 - Bullseye] (Mine-Blade-Battlegear-2-Mod-1.7.10.jar) 
	GL info: ' Vendor: 'Intel' Version: '4.3.0 - Build 20.19.15.4835' Renderer: 'Intel(R) HD Graphics 4400'
	Launched Version: 1.7.10-Forge10.13.4.1614-1.7.10
	LWJGL: 2.9.1
	OpenGL: Intel(R) HD Graphics 4400 GL version 4.3.0 - Build 20.19.15.4835, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: [vanilla, file/ISP [v2.0] ~by Insanial.zip]
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by BladeAnimation** [comment]
my minecraft world doesnt load in its just stuck on the tiltle screen
